export const PROFILE = {
  nameEn: 'Mohammed Al Nuaimi',
  nameAr: 'محمد النعيمي',
  titleEn: 'CTO Office',
  titleAr: 'مكتب الرئيس التنفيذي للتقنية',
  roleEn: 'CTO Office',
  roleAr: 'مكتب الرئيس التنفيذي للتقنية',
  email: 'm.alnuaimi@diriyah.sa',
  avatar: '',
  departmentEn: 'CTO Office',
  departmentAr: 'مكتب الرئيس التنفيذي للتقنية',
  ministryEn: 'Diriyah',
  ministryAr: 'الدرعية',
  mobile: '+966 50 000 0000',
  altEmail: '',
}
